/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchesFixtureIdRouteImport } from './routes/matches.$fixtureId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesFixtureIdRoute = MatchesFixtureIdRouteImport.update({
  id: '/matches/$fixtureId',
  path: '/matches/$fixtureId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/matches/$fixtureId': typeof MatchesFixtureIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/matches/$fixtureId': typeof MatchesFixtureIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/matches/$fixtureId': typeof MatchesFixtureIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/matches/$fixtureId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/matches/$fixtureId'
  id: '__root__' | '/' | '/matches/$fixtureId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MatchesFixtureIdRoute: typeof MatchesFixtureIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$fixtureId': {
      id: '/matches/$fixtureId'
      path: '/matches/$fixtureId'
      fullPath: '/matches/$fixtureId'
      preLoaderRoute: typeof MatchesFixtureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MatchesFixtureIdRoute: MatchesFixtureIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
