/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompetitionsRouteImport } from './routes/competitions'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as CompetitionsIndexRouteImport } from './routes/competitions.index'
import { Route as CompetitionsLeagueIdRouteImport } from './routes/competitions.$leagueId'
import { Route as MatchesFixtureIdRouteImport } from './routes/matches.$fixtureId'
import { Route as PlayersIndexRouteImport } from './routes/players.index'
import { Route as PlayersPlayerIdRouteImport } from './routes/players.$playerId'
import { Route as TeamsTeamIdRouteImport } from './routes/teams.$teamId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsRoute = CompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsIndexRoute = CompetitionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompetitionsRoute,
} as any)
const CompetitionsLeagueIdRoute = CompetitionsLeagueIdRouteImport.update({
  id: '/$leagueId',
  path: '/$leagueId',
  getParentRoute: () => CompetitionsRoute,
} as any)
const MatchesFixtureIdRoute = MatchesFixtureIdRouteImport.update({
  id: '/matches/$fixtureId',
  path: '/matches/$fixtureId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayersRoute,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/$playerId',
  path: '/$playerId',
  getParentRoute: () => PlayersRoute,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/competitions': typeof CompetitionsRouteWithChildren
  '/players': typeof PlayersRouteWithChildren
  '/competitions/$leagueId': typeof CompetitionsLeagueIdRoute
  '/matches/$fixtureId': typeof MatchesFixtureIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/competitions/': typeof CompetitionsIndexRoute
  '/players/': typeof PlayersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/competitions/$leagueId': typeof CompetitionsLeagueIdRoute
  '/matches/$fixtureId': typeof MatchesFixtureIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/competitions': typeof CompetitionsIndexRoute
  '/players': typeof PlayersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/competitions': typeof CompetitionsRouteWithChildren
  '/players': typeof PlayersRouteWithChildren
  '/competitions/$leagueId': typeof CompetitionsLeagueIdRoute
  '/matches/$fixtureId': typeof MatchesFixtureIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/competitions/': typeof CompetitionsIndexRoute
  '/players/': typeof PlayersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/competitions'
    | '/players'
    | '/competitions/$leagueId'
    | '/matches/$fixtureId'
    | '/players/$playerId'
    | '/teams/$teamId'
    | '/competitions/'
    | '/players/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/competitions/$leagueId'
    | '/matches/$fixtureId'
    | '/players/$playerId'
    | '/teams/$teamId'
    | '/competitions'
    | '/players'
  id:
    | '__root__'
    | '/'
    | '/competitions'
    | '/players'
    | '/competitions/$leagueId'
    | '/matches/$fixtureId'
    | '/players/$playerId'
    | '/teams/$teamId'
    | '/competitions/'
    | '/players/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompetitionsRoute: typeof CompetitionsRouteWithChildren
  PlayersRoute: typeof PlayersRouteWithChildren
  MatchesFixtureIdRoute: typeof MatchesFixtureIdRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions': {
      id: '/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions/': {
      id: '/competitions/'
      path: '/'
      fullPath: '/competitions/'
      preLoaderRoute: typeof CompetitionsIndexRouteImport
      parentRoute: typeof CompetitionsRoute
    }
    '/competitions/$leagueId': {
      id: '/competitions/$leagueId'
      path: '/$leagueId'
      fullPath: '/competitions/$leagueId'
      preLoaderRoute: typeof CompetitionsLeagueIdRouteImport
      parentRoute: typeof CompetitionsRoute
    }
    '/matches/$fixtureId': {
      id: '/matches/$fixtureId'
      path: '/matches/$fixtureId'
      fullPath: '/matches/$fixtureId'
      preLoaderRoute: typeof MatchesFixtureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof PlayersRoute
    }
    '/players/$playerId': {
      id: '/players/$playerId'
      path: '/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof PlayersRoute
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CompetitionsRouteChildren {
  CompetitionsLeagueIdRoute: typeof CompetitionsLeagueIdRoute
  CompetitionsIndexRoute: typeof CompetitionsIndexRoute
}

const CompetitionsRouteChildren: CompetitionsRouteChildren = {
  CompetitionsLeagueIdRoute: CompetitionsLeagueIdRoute,
  CompetitionsIndexRoute: CompetitionsIndexRoute,
}

const CompetitionsRouteWithChildren = CompetitionsRoute._addFileChildren(
  CompetitionsRouteChildren,
)

interface PlayersRouteChildren {
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
}

const PlayersRouteChildren: PlayersRouteChildren = {
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
  PlayersIndexRoute: PlayersIndexRoute,
}

const PlayersRouteWithChildren =
  PlayersRoute._addFileChildren(PlayersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompetitionsRoute: CompetitionsRouteWithChildren,
  PlayersRoute: PlayersRouteWithChildren,
  MatchesFixtureIdRoute: MatchesFixtureIdRoute,
  TeamsTeamIdRoute: TeamsTeamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
